### PR TITLE
Static html build

### PR DESCRIPTION
**Pull request by ericnost**
@Frijol - Here is the full final version of the notebook. If you could run it ASAP to build the static HTML version, that would be ideal, because then the data will match what's in the doc right now.

### CODE REVIEW

**Comment by ericnost** [comment]
Thanks @Frijol ! Could you remind me how we take https://github.com/edgi-govdata-archiving/ECHO-COVID19/blob/static-html-build/ECHO_COVID19_pg_run.html and make it publicly viewable as web page?

**Comment by Frijol** [comment]
Just prepend https://htmlpreview.github.io/? to any github-hosted HTML page!

**Review by Frijol — APPROVED** [review]
My only q is: do we want to change titles and legends and axes to "reported violations" language here before publishing? Esp to match what @lesliealanis is working on

**Comment by ericnost** [comment]
I worry about the database not working and I was wondering if the language change could be something Leslie could look at in reformatting the charts (not sure how she's doing it!) At the very least, the text will make it clear that we mean _reported_ violations

**Comment by ericnost** [comment]
That said, I think you have a clear sense of where this language needs to change and where it doesn't, so I would welcome you to re-run it with those changes!

**Comment by Frijol** [comment]
Let's go ahead with this as is for now!

@lesliealanis is manipulating the images in Paint 3D so she can make it say whatever she wants but can't do stacked bar charts. Maybe @maalvikabhat would have time to look at (a) changing language in titles/axes/legends to say "Reported Violations" and (b) create a stacked bar chart which stacks failures to report on top of known violations for CWA violations?

**Pull request merged**
